name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print a welcom message
        run: echo "Welcom to our first Github Actions Workflow!"

      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: list repository files
        run: ls -la
