on:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "src/**"
  pull_request:
    branches:
      - main
      - "release/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: chechkout code
        uses: actions/chechkout@v5.0.0
      
      - name: Run Tests
        run: npm test
